name: Lint Go
on:
  push:
    branches:
      - master

jobs:
  goLint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1.7.0
	with:
	  go-version: '1.17.10'

      - name: Lint
        run: |
          go mod tidy -compat=1.17
          gofmt -l -s -w .
          go vet
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
	  version: "2022.1.1"
          install-go: false
	  cache-key: '1.17.10'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'RoseLoverX: auto fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: AmarnathCjd
          commit_user_email: 72609355+AmarnathCjd@users.noreply.github.com
          commit_author: AmarnathCjd <72609355+AmarnathCjd+@users.noreply.github.com>
          
